
local killCountProps = {
	neutral_novice = 1, neutral_experienced = 2, neutral_veteran = 3, neutral_master = 4,
	monolith_novice = 1, monolith_experienced = 2, monolith_veteran = 3, monolith_master = 4,
	military_novice = 1, military_experienced = 2, military_veteran = 3, military_master = 4,
	killer_novice = 1, killer_experienced = 2, killer_veteran = 3, killer_master = 4,
	ecolog_novice = 1, ecolog_experienced = 2, ecolog_veteran = 3, ecolog_master = 4,
	dolg_novice = 1, dolg_experienced = 2, dolg_veteran = 3, dolg_master = 4,
	freedom_novice = 1, freedom_experienced = 2, freedom_veteran = 3, freedom_master = 4,
	bandit_novice = 1, bandit_experienced = 2, bandit_veteran = 3, bandit_master = 4,
	zombied_novice = 1, zombied_experienced = 2, zombied_veteran = 3, zombied_master = 4,
	stranger_novice = 1, stranger_experienced = 2, stranger_veteran = 3, stranger_master = 4,
	
	trader_novice = 1, trader_experienced = 2, trader_veteran = 3, trader_master = 4,
	cnn_novice = 1, cnn_experienced = 2, cnn_veteran = 3, cnn_master = 4,
	exmon_novice = 1, exmon_experienced = 2, exmon_veteran = 3, exmon_master = 4,
	apclps_novice = 1, apclps_experienced = 2, apclps_veteran = 3, apclps_master = 4,
	head_hunter_novice = 1, head_hunter_experienced = 2, head_hunter_veteran = 3, head_hunter_master = 4,
	bb_novice = 1, bb_experienced = 2, bb_veteran = 3, bb_master = 4,
	degenerate_novice = 1, degenerate_experienced = 2, degenerate_veteran = 3, degenerate_master = 4,
	gm_group_novice = 1, gm_group_experienced = 2, gm_group_veteran = 3, gm_group_master = 4,
	militia_novice = 1, militia_experienced = 2, militia_veteran = 3, militia_master = 4,
	omon_novice = 1, omon_experienced = 2, omon_veteran = 3, omon_master = 4,
	sbu_novice = 1, sbu_experienced = 2, sbu_veteran = 3, sbu_master = 4,
	mvd_novice = 1, mvd_experienced = 2, mvd_veteran = 3, mvd_master = 4,
	mchs_novice = 1, mchs_experienced = 2, mchs_veteran = 3, mchs_master = 4,
	vympel_novice = 1, vympel_experienced = 2, vympel_veteran = 3, vympel_master = 4,
	alfa_novice = 1, alfa_experienced = 2, alfa_veteran = 3, alfa_master = 4,
	fsin_novice = 1, fsin_experienced = 2, fsin_veteran = 3, fsin_master = 4,
	MZ_novice = 1, MZ_experienced = 2, MZ_veteran = 3, MZ_master = 4,
	prokuratura_novice = 1, prokuratura_experienced = 2, prokuratura_veteran = 3, prokuratura_master = 4,
	gosdep_novice = 1, gosdep_experienced = 2, gosdep_veteran = 3, gosdep_master = 4,
                    nalogs_novice = 1, nalogs_experienced = 2, nalogs_veteran = 3, nalogs_master = 4,
	SK_novice = 1, SK_experienced = 2, SK_veteran = 3, SK_master = 4,
	STO_novice = 1, STO_experienced = 2, STO_veteran = 3, STO_master = 4,
	sabbers_novice = 1, sabbers_experienced = 2, sabbers_veteran = 3, sabbers_master = 4,
	operators_novice = 1, operators_experienced = 2, operators_veteran = 3, operators_master = 4,
	TOK_novice = 1, TOK_experienced = 2, TOK_veteran = 3, TOK_master = 4,
	TSZV_novice = 1, TSZV_experienced = 2, TSZV_veteran = 3, TSZV_master = 4,
	korsin_novice = 1, korsin_experienced = 2, korsin_veteran = 3, korsin_master = 4,
	TB_novice = 1, TB_experienced = 2, TB_veteran = 3, TB_master = 4,
	TOCHK_novice = 1, TOCHK_experienced = 2, TOCHK_veteran = 3, TOCHK_master = 4,
	sekZ_novice = 1, sekZ_experienced = 2, sekZ_veteran = 3, sekZ_master = 4,
	GISK_novice = 1, GISK_experienced = 2, GISK_veteran = 3, GISK_master = 4,
	
	tushkano_weak = 1,
	flesh_weak = 1, flesh_normal = 2, flesh_strong = 3,
	boar_weak = 1, boar_normal = 2, boar_strong = 3,
	dog_weak = 1, dog_normal = 2, dog_strong = 3,
	pseudodog_weak = 1, pseudodog_normal = 2, pseudodog_strong = 3,
	psy_dog_weak = 1, psy_dog_normal = 2, psy_dog_strong = 3,
	snork_weak = 2, snork_normal = 3, snork_strong = 4,
	poltergeist_weak = 2,
	pseudo_gigant_weak = 4,
	controller_weak = 4,
	bloodsucker_weak = 1, bloodsucker_normal = 2, bloodsucker_strong = 3,
	zombie_weak = 1, zombie_normal = 2, zombie_strong = 3,
	burer_weak = 1, burer_normal = 2, burer_strong = 3,
	cat_weak = 1, cat_normal = 2, cat_strong = 3,
	chimera_weak = 1, chimera_normal = 2, chimera_strong = 3,
	fracture_weak = 1, fracture_normal = 2, fracture_strong = 3
	 
	
}

local sect_alias = {	
	tushkano_normal = "tushkano_weak", tushkano_strong = "tushkano_weak",
	poltergeist_normal = "poltergeist_weak", poltergeist_strong = "poltergeist_weak",
	pseudo_gigant_normal = "pseudo_gigant_weak", pseudo_gigant_strong = "pseudo_gigant_weak",
	controller_normal = "controller_weak", controller_strong = "controller_weak",
	psy_dog_weak = "psy_dog", psy_dog_normal = "psy_dog", psy_dog_strong = "psy_dog", rad_psy_dog = "psy_dog",
	zombie_weak = "zombie_weak", zombie_normal  = "zombie_normal", zombie_strong = "zombie_strong",
	burer_weak = "burer_weak", burer_normal = "burer_normal", burer_strong = "burer_strong",
	cat_weak = "cat_weak", cat_normal = "cat_normal", cat_strong = "cat_strong",
	chimera_weak = "chimera_weak", chimera_normal = "chimera_normal", chimera_strong = "chimera_strong",
	fracture_weak = "fracture_weak", fracture_normal = "fracture_normal", fracture_strong = "fracture_strong"
}

monster_classes = {
			[clsid.tushkano_s    ] = "tushkano",
			[clsid.flesh_s       ] = "flesh",
			[clsid.boar_s        ] = "boar",
			[clsid.burer_s       ] = "burer",
			[clsid.cat_s         ] = "cat",
			[clsid.chimera_s     ] = "chimera",
			[clsid.fracture_s    ] = "fracture",
			[clsid.dog_s         ] = "dog",
			[clsid.pseudodog_s   ] = "pseudodog",
			[clsid.psy_dog_s     ] = "psy_dog",
			[clsid.psy_dog_phantom_s] = "NIL",
			[clsid.snork_s       ] = "snork",
			[clsid.poltergeist_s ] = "poltergeist",
			[clsid.gigant_s      ] = "pseudo_gigant",
			[clsid.controller_s  ] = "controller",
			[clsid.bloodsucker_s ] = "bloodsucker",
			[clsid.zombie_s      ] = "zombie"
		}		


function addKillCount(npc)
	local props, sect = getNpcType(npc)
	if props == nil then
		return
	end

	local sect_name
	if sect_alias[sect] ~= nil then
		sect_name = sect_alias[sect]
	else
		sect_name = sect
	end

	if killCountProps[sect_name] == nil then
--'		print_table(sect_alias)
--'		abort("Statistic ERROR: required section [%s] not present, based [%s]", tostring(sect_name), tostring(sect))
		return
	end
	actor_stats.add_points(props, sect_name, 1, killCountProps[sect_name])
	db.actor:set_character_rank(db.actor:character_rank() + killCountProps[sect_name])
end


function getNpcType(npc)
	if IsStalker(npc) then
		local community = "neutral"
		if npc:character_community() == "monolith" then
			community = "monolith"
		elseif npc:character_community() == "military" then
			community = "military"
		elseif npc:character_community() == "killer" then
			community = "killer"
		elseif npc:character_community() == "ecolog" then
			community = "ecolog"
		elseif npc:character_community() == "dolg" then
			community = "dolg"
		elseif npc:character_community() == "freedom" then
			community = "freedom"
		elseif npc:character_community() == "bandit" then
			community = "bandit"
		elseif npc:character_community() == "zombied" then
			community = "zombied"
		elseif npc:character_community() == "stranger" then
			community = "stranger"
		elseif npc:character_community() == "cnn" then
			community = "cnn"
		elseif npc:character_community() == "exmon" then
			community = "exmon"
		elseif npc:character_community() == "apclps" then
			community = "apclps"
		elseif npc:character_community() == "head_hunter" then
			community = "head_hunter"
		elseif npc:character_community() == "trader" then
			community = "trader"
		elseif npc:character_community() == "bb" then
			community = "bb"
		elseif npc:character_community() == "degenerate" then
			community = "degenerate"
		elseif npc:character_community() == "gm_group" then
			community = "gm_group"
			elseif npc:character_community() == "militia" then
			community = "militia"
		elseif npc:character_community() == "omon" then
			community = "omon"
		elseif npc:character_community() == "sbu" then
			community = "sbu"
		elseif npc:character_community() == "mvd" then
			community = "mvd"
		elseif npc:character_community() == "mchs" then
			community = "mchs"
		elseif npc:character_community() == "vympel" then
			community = "vympel"
		elseif npc:character_community() == "alfa" then
			community = "alfa"
		elseif npc:character_community() == "fsin" then
			community = "fsin"
		elseif npc:character_community() == "MZ" then
			community = "MZ"
		elseif npc:character_community() == "prokuratura" then
			community = "prokuratura"
		elseif npc:character_community() == "gosdep" then
			community = "gosdep"
		elseif npc:character_community() == "nalogs" then
			community = "nalogs"
		elseif npc:character_community() == "SK" then
			community = "SK"
		elseif npc:character_community() == "STO" then
			community = "STO"
		elseif npc:character_community() == "sabbers" then
			community = "sabbers"
		elseif npc:character_community() == "operators" then
			community = "operators"
		elseif npc:character_community() == "TOK" then
			community = "TOK"
		elseif npc:character_community() == "TSZV" then
			community = "TSZV"
		elseif npc:character_community() == "korsin" then
			community = "korsin"
		elseif npc:character_community() == "TB" then
			community = "TB"
		elseif npc:character_community() == "TOCHK" then
			community = "TOCHK"
		elseif npc:character_community() == "sekZ" then
			community = "sekZ"
		elseif npc:character_community() == "GISK" then
			community = "GISK"
		end
		local rank = ranks.get_obj_rank_name(npc)
		return "stalkerkills", community.."_"..rank
	else
		local community = monster_classes[get_clsid(npc)]
		if community == nil then
			abort("Statistic ERROR: cannot find monstr class for [%s]", npc:name())
		end
		if community == "NIL" then
			return nil,nil
		end
		
		local rank = ranks.get_obj_rank_name(npc)
		return "monsterkills", community.."_"..rank
	end	
end


